server:
  port: 8082
spring:
  thymeleaf:
    encoding: UTF-8
    cache: false #çƒ­éƒ¨ç½²é™æ€æ–‡ä»¶ï¼Œç¦æ­¢ç¼“å­˜
    mode: HTML5 #ä½¿ç”¨HTML5æ ‡å‡†
#é…ç½®æ•°æ®æº?
  datasource:
    username: root
    password: '123456'
    url: jdbc:mysql://localhost/scwvg?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
#    hibernate:
#      ddl-auto: update #è‡ªåŠ¨æ›´æ–°å»ºè¡¨
    show-sql: true
#    database-platform: org.hibernate.dialect.MySQLDialect # é…ç½®æ•¸æ“šåº«æ–¹è¨?
  #é…ç½®å›½é™…åŒ–æ ¡éªŒçš„propertiesæ–‡ä»¶
  messages:
    basename: i18n/validation/ValidationMessages
  #springbootä¹‹jsonä¸­æ—¥æœŸæ ¼å¼è½¬æ¢é—®é¢?
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8