server:
  port: 6202
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.scwvg.entitys
spring:
  application:
    name: scwvg-pmee-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pmee1
    username: root
    password: lul@123456
    #配置初始化大小/最小/最大
    initial-size: 1
    min-idle: 1
    max-active: 20
    #获取连接等待超时时间
    max-wait: 60000
    #间隔多久进行一次检测，检测需要关闭的空闲连接
    time-between-eviction-runs-millis: 60000
    #一个连接在池中最小生存的时间
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT ‘x’
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
    pool-prepared-statements: false
    max-pool-prepared-statement-per-connection-size: 20
eureka:
  client:
    service-url:
      defaultZone: http://scwvg-eureka7601.com:7601/eureka/,http://scwvg-eureka7602.com:7602/eureka/,http://scwvg-eureka7603.com:7603/eureka/
  instance:
    instance-id: scwvg-pmee-provider-6202
    prefer-ip-address: true
info:
  app.name: scwvg-pmee-provider
  company.name: www.scwvg.com
  build.artifactId: scwvg-pmee-6202
  build.version: 1.0-SNAPSHOT